[2024-11-25T23:55:35.014+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T23:55:35.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_games_etl_daily.load_data scheduled__2024-11-24T02:30:00+00:00 [queued]>
[2024-11-25T23:55:35.040+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_games_etl_daily.load_data scheduled__2024-11-24T02:30:00+00:00 [queued]>
[2024-11-25T23:55:35.040+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-25T23:55:35.049+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-11-24 02:30:00+00:00
[2024-11-25T23:55:35.055+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_games_etl_daily', 'load_data', 'scheduled__2024-11-24T02:30:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/daily_data_etl.py', '--cfg-path', '/tmp/tmp8w56aepp']
[2024-11-25T23:55:35.056+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask load_data
[2024-11-25T23:55:35.057+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=271) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T23:55:35.057+0000] {standard_task_runner.py:63} INFO - Started process 277 to run task
[2024-11-25T23:55:35.086+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_games_etl_daily.load_data scheduled__2024-11-24T02:30:00+00:00 [running]> on host 98bc2e09bbb2
[2024-11-25T23:55:35.145+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_games_etl_daily' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-24T02:30:00+00:00'
[2024-11-25T23:55:35.146+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T23:55:35.336+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-25T23:55:35.611+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-25T23:55:41.933+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-25T23:55:41.934+0000] {logging_mixin.py:188} INFO - An error occurred: 002003 (42S02): 01b89e1b-0004-386c-0002-58cf00032562: SQL compilation error:
Table 'NBASTATS.RAW_DATA.NBA_GAMES_STAGING' does not exist or not authorized.
[2024-11-25T23:55:41.934+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T23:55:41.934+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_data_etl.py", line 145, in load_data
    raise e
  File "/opt/airflow/dags/daily_data_etl.py", line 138, in load_data
    con.execute(drop_staging_table_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01b89e1b-0004-386c-0002-58cf00032562: SQL compilation error:
Table 'NBASTATS.RAW_DATA.NBA_GAMES_STAGING' does not exist or not authorized.
[2024-11-25T23:55:41.941+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_games_etl_daily, task_id=load_data, run_id=scheduled__2024-11-24T02:30:00+00:00, execution_date=20241124T023000, start_date=20241125T235535, end_date=20241125T235541
[2024-11-25T23:55:41.950+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task load_data (002003 (42S02): 01b89e1b-0004-386c-0002-58cf00032562: SQL compilation error:
Table 'NBASTATS.RAW_DATA.NBA_GAMES_STAGING' does not exist or not authorized.; 277)
[2024-11-25T23:55:41.996+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-25T23:55:42.007+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T23:55:42.009+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
